
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';


export const REGISTRO_EXISTOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const CERRAR_SESION = 'CERRAR_SESION';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';

export const FORMULARIO_RESERVACION = 'FORMULARIO_RESERVACION' 
export const OBTENER_RESERVACIONES = 'OBTENER_RESERVACIONES' 
export const AGREGAR_RESERVACION = 'AGREGAR_RESERVACION' 
export const RESERVACION_ACTUAL = ' RESERVACION_ACTUAL'
export const ELIMINAR_RESERVACION = 'ELIMINAR_RESERVACION'
export const RESERVACION_ERROR = 'RESERVACION_ERROR'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const ACTUALIZAR_RESERVACION = 'ACTUALIZAR_RESERVACION' 


export const FORMULARIO_FACTURA = 'FORMULARIO_FACTURA' 
export const OBTENER_FACTURAS = 'OBTENER_FACTURAS' 
export const AGREGAR_FACTURA = 'AGREGAR_FACTURA'  
export const FACTURA_ACTUAL = ' FACTURA_ACTUAL'
export const ELIMINAR_FACTURA = 'ELIMINAR_FACTURA'
export const FACTURA_ERROR = 'FACTURA_ERROR'
export const ACTUALIZAR_FACTURA = 'ACTUALIZAR_FACTURA'  
